version: "3.4"

services:
  app-a:
    build: ./fastapi_app/
    # image: ghcr.io/blueswen/fastapi-jaeger/app:latest
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-grpc"
      OTEL_SERVICE_NAME: "app-a"
      OTLP_GRPC_ENDPOINT: "otel-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
  
  app-b:
    build: ./fastapi_app/
    # image: ghcr.io/blueswen/fastapi-jaeger/app:latest
    ports:
      - "8001:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-grpc"
      OTEL_SERVICE_NAME: "app-b"
      OTLP_GRPC_ENDPOINT: "otel-collector:4317"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"
  
  app-c:
    build: ./fastapi_app/
    # image: ghcr.io/blueswen/fastapi-jaeger/app:latest
    ports:
      - "8002:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-http"
      OTEL_SERVICE_NAME: "app-c"
      OTLP_HTTP_ENDPOINT: "http://otel-collector:4318/v1/traces"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"

  app-d:
    build: ./fastapi_app/
    # image: ghcr.io/blueswen/fastapi-jaeger/app:latest
    ports:
      - "8003:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      MODE: "otlp-http"
      OTEL_SERVICE_NAME: "app-d"
      OTLP_HTTP_ENDPOINT: "http://otel-collector:4318/v1/traces"
      TARGET_ONE_HOST: "app-b"
      TARGET_TWO_HOST: "app-c"

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.52.0
    command: 
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--collector.otlp.enabled=true"
    environment: 
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - "4317" # accept OpenTelemetry Protocol (OTLP) over gRPC
      - "4318" # accept OpenTelemetry Protocol (OTLP) over HTTP
      - "14250" # accept model.proto
    restart: on-failure
    depends_on:
      - cassandra-schema

  cassandra:
    image: cassandra:4.1.2

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.52.0
    depends_on:
      - cassandra

  jaeger-query:
    image: jaegertracing/jaeger-query:1.52.0
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    command:
      - "--cassandra.keyspace=jaeger_v1_dc1"
      - "--cassandra.servers=cassandra"
      - "--prometheus.query.support-spanmetrics-connector=true"
      - "--prometheus.server-url=http://prometheus:9090"
      - "--prometheus.query.normalize-duration=true"
      - "--prometheus.query.normalize-calls=true"
    ports:
      - "16686:16686"
      - "16687:16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./etc/otel-collector-config-spm.yaml:/conf/config.yaml
    ports:
      - "4317" # OTLP gRPC receiver
      - "4318" # OTLP http receiver
      - "8889" # Prometheus metrics exporter
    restart: on-failure
    depends_on:
      - jaeger-collector

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yml:/workspace/prometheus.yml
    command:
      - --config.file=/workspace/prometheus.yml
